### ISSUE TITLE
How the Ab1Wrapper analyze the sequence data?

### ISSUE THREAD

**Issue by tiger2014** [Funny-Silkie/Ab1Analyzer#1]
Hi Silkie,

I read the code:

`data = Ab1Data.Create(value);               
                wrapper = new Ab1Wrapper(data);`

But I don't understand how the 'new Ab1Wrapper(data)' analyzes the data. I have debugged it but found out that no other function was called when the code create a new  Ab1Wrapper object.

Can you tell me how the data was analyzed?

Thanks

**Comment by Funny-Silkie** [comment]
Hi tiger.

Thank you for asking.

First, let me explain briefly about `Ab1Data` and `Ab1Wrapper` classes.
`Ab1Data` has ABIF analyzed data in `Data` property. As the name says, `Ab1Wrapper` functions as a wrapper of `Ab1Wrapper`.

Here, I explain for your question.
When you call `Ab1Data.Create(string)`, all data from ABIF file is analyzed instantly and put into `Data` property. `Ab1Wrapper` get data from `Data` property from `Ab1Data` class. To get data  from `Data` property (`Ab1DirectoryCollection`), tag name (string value) and tag number (integer value) is needed. `Ab1Wrapper` use specific tag name and tag number to get data. For example, you can get DNA sequence predicated by sequencer by using `"PBAS"` and `2`.
If you want to use `AdvancedAnalysisData` property of `Ab1Wrapper`, you must call `Ab1Wrapper.AnalyzeSequence(int, int, bool)` advancely. `AdvancedAnalysisData` is my original implementation of predicating sequence. But, the accuracy is mush lower than analysis of sequencer. I recommend you not to use `AdvancedAnalysisData`.

If you want to know tag name and tag number information, reference https://projects.nfstc.org/workshops/resources/articles/ABIF_File_Format.pdf. But, This document is too old to cover all tags. Please be careful.

Sorry for poor English.
If you have any question, please ask me again :)

Thanks!

**Comment by tiger2014** [comment]
Hi Silkie,

Thank you for your response.

I fully understand this question and will reach out to you if any more questions. 

Thanks!
